openapi: 3.0.4
info:
  title: Price Tracker API
  version: 2026.0.0-dev
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: X-Api-Key
      in: header
  schemas:
    User:
      type: object
      required:
        - email
      properties:
        uuid:
          type: string
          format: uuid
          readOnly: true
        email:
          type: string
          format: email
          example: user.name@example.org
    Product:
      type: object
      required:
       - name
       - url
      properties:
        hruid:
          type: string
          readOnly: true
        user:
          type: string
          readOnly: true
        name:
          type: string
          example: Teddy Bear
        url:
          type: string
          format: uri
          example: https://www.example.org/product
        active:
          type: boolean
          default: true
          example: true
    Price:
      type: object
      required:
       - value
       - timestamp
      properties:
        value:
          type: number
          example: 9.99
        timestamp:
          type: string
          format: date-time
          example: "2020-03-14T15:32:52"
  headers:
    X-Api-Key:
      description: Api key used for authorization
      schema:
        type: string
        example: secretApiKey
security:
 - api_key: []

