/* Most of the code here was generated by AI */

import { setState } from "./state.js";
import { renderWorkspace } from "./render.js";

/**
 * Navigates to the products list view, clearing the current product selection.
 * @param {string} [view] - Optional product list filter: "all" or "mine".
 */
export function navigateToProducts(view) {
    const partial = {
        currentView: "products",
        currentProduct: null,
        showAddProductForm: false,
        showAddPriceForm: false,
    };
    if (view) { partial.productListView = view; }
    setState(partial);
    renderWorkspace();
}

/**
 * Navigates to a specific product list filter view.
 * @param {string} view - The product list filter: "all" or "mine".
 */
export function navigateToView(view) {
    setState({
        currentView: "products",
        currentProduct: null,
        showAddProductForm: false,
        showAddPriceForm: false,
        productListView: view,
    });
    localStorage.setItem("productListView", view);
    renderWorkspace();
}

/**
 * Navigates to the detail view for a specific product.
 * @param {string} hruid - The product's human-readable UID.
 */
export function navigateToProduct(hruid) {
    setState({
        currentView: "productDetail",
        currentProduct: hruid,
        showAddProductForm: false,
        showAddPriceForm: false,
    });
    renderWorkspace();
}
